version: '3'
services:
    manager-nginx:
        build:
            context: ./manager/docker/development
            dockerfile: nginx.docker
        volumes: 
            - ./manager:/app
        depends_on: 
            - manager-php-fpm
        ports: 
            - "8000:8000"
    manager-php-fpm:
        build:
            context: ./manager/docker/development
            dockerfile: php-fpm.docker
        environment:
            APP_DEBUG: 1
        volumes: 
            - ./manager:/app
        depends_on:
            - manager-postgres
    manager-apache:
        build:
            context: ./manager/docker/development
            dockerfile: apache.docker
        volumes:
            - ./manager:/app
        ports:
            - "8080:80"
    manager-php-cli:
        build:
            context: ./manager/docker/development
            dockerfile: php-cli.docker
        environment:
            APP_DEBUG: 1
        volumes: 
            - ./manager:/app
            - composer:/root/.composer/cache
        depends_on:
            - manager-postgres
    manager-postgres:
        image: postgres:11.2-alpine
        volumes:
            - manager-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"

    mailer:
        image: mailhog/mailhog
        ports:
            - "8082:8025"
            
volumes:
    manager-postgres:
    composer:

