version: '3'
services:
    manager-nginx:
        image: ${REGISTRY_ADDRESS}/manager-nginx:${IMAGE_TAG}
        restart: always
        depends_on: 
            - manager-php-fpm
        ports: 
            - "8000:8000"
    manager-php-fpm:
        image: ${REGISTRY_ADDRESS}/manager-php-fpm:${IMAGE_TAG}
        restart: always
    manager-apache:
        image: ${REGISTRY_ADDRESS}/manager-apache:${IMAGE_TAG}
        restart: always
        ports:
            - "8080:80"
    php-cli:
        image: ${REGISTRY_ADDRESS}/manager-php-cli:${IMAGE_TAG}
        


